import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coding Hunters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h3 className={styles.title}>&lt;Coding Hunter/&gt;</h3>
        <span className={styles.spanimg}>
        {/* <Image className={styles.imgcode} src='/codeimg.avif '  height={150} width={200} alt='Coding Hunter'/> */}
        <img className={styles.imgcode} src='/codeimg.avif '  height={150} width={200} alt='Coding Hunter'/>
        </span>
        <p className={styles.description}>
          A Blog to Hunt Coders around the globe
        </p>
        <div className={styles.mainblogs}>
          <h1>Popular Blogs</h1>
          <div className="blogItems">
            <h3>How to learn Next Js in 2022?.</h3>
            <p>Welcome to the Next.js Foundations course! This beginner-friendly, example-led course ...</p>
          </div>
          <div className="blogItems">
            <h3>How to learn Python in 2022?</h3>
            <p>A Coursera Specialization is a series of courses that helps you master a skill ... </p>
          </div>
          <div className="blogItems">
            <h3>How to learn Flutter in 2022? </h3>
            <p>Welcome to the Complete Flutter App Development Bootcamp with Dart ...</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
}
